[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib", "../../../defihackLabs/lib"]
fs_permissions = [{ access = "read", path = "./" }]
evm_version = "shanghai"

[rpc_endpoints]
bsc = "https://binance.llamarpc.com"
